# Task 1 - Brush up all basics python concepts. 

## basics python functions and libraries
### functions 
#### Creating Arrays:

numpy.array: Create an array from a Python list or tuple.

numpy.zeros: Create an array filled with zeros.

numpy.ones: Create an array filled with ones.

numpy.arange: Create an array with values in a given range.

numpy.random: Generate arrays with random numbers.

#### Array Attributes:

ndarray.shape: Returns the dimensions of the array.

ndarray.ndim: Returns the number of array dimensions.

ndarray.size: Returns the total number of elements in the array.

ndarray.dtype: Returns the data type of the elements in the array.

#### Array Operations:

ndarray.reshape: Reshape an array into a new shape.

ndarray.concatenate: Concatenate arrays along a specified axis.

ndarray.transpose: Permute the dimensions of an array.

ndarray.sort: Sort the elements of an array.

#### Mathematical Functions:

numpy.add: Element-wise addition of arrays.

numpy.subtract: Element-wise subtraction of arrays.

numpy.multiply: Element-wise multiplication of arrays.

numpy.divide: Element-wise division of arrays.

numpy.dot: Matrix multiplication of two arrays.

#### Aggregation Functions:

numpy.sum: Compute the sum of array elements.

numpy.mean: Compute the arithmetic mean along a specified axis.

numpy.min: Find the minimum value in an array.

numpy.max: Find the maximum value in an array.

numpy.std: Compute the standard deviation along a specified axis.

### libraries

### Matplotlib
The plotting of numerical data is the responsibility of this library. It's for this reason that it's used in analysis of data. It's an open-source library that plots high-definition figures such as pie charts, scatterplots, boxplots, and graphs, among other things.

### NumPy
NumPy is one of the most widely used open-source Python packages, focusing on mathematical and scientific computation. It has built-in mathematical functions for convenient computation and facilitates large matrices and multidimensional data. It can be used for various things, including linear algebra, as an N-dimensional container for all types of data. The NumPy Array Python object defines an N-dimensional array with rows and columns. A long with this, it can be used as a random number generator.

In Python, NumPy is recommended over lists because it uses less memory, is faster, and is more convenient.

Images, sound waves, and other binary raw streams can be represented as a multidimensional array of real values using the NumPy interface for visualization. Full-stack developers must be familiar with Numpy to use this machine learning library.

### Pandas
Pandas is an open source library licenced under the Berkeley Software Distribution (BSD). In the domain of data science, this well-known library is widely used. They're mostly used for analysis, manipulation, and cleaning of data, among other things. Pandas allows us to perform simple data modelling and analysis without having to swap to another language like R.

### Seaborn
Visualization of statistical models is possible with this package. The library is largely based on Matplotlib and enables the formation of statistical graphics via:

Variable comparison via an API based on datasets

Create complex visualisations with ease, including multi-plot grids.

Univariate and bivariate visualisations are used to compare data subsets.

Patterns can be displayed in a variety of colour palettes.

Linear regression estimation and plotting are done automatically.

#### A tuple is a Python data type used to store collections of data, similar to a list.

# Task 2- Reshape a 1D NumPy array of length 12 into a 2D array of shape (3, 4).

In [1]:
import numpy as np

In [2]:
#creating an array of length 12
# generates random integers from a given range 
d1 = np.random.randint(0, 20, size=12)

In [3]:
print(d1)

[ 6  4  4  8 11 11  4  1  6  7 18  9]


In [4]:
#reshaping 1D array into rows and colums 
D2=d1.reshape(3,4)

In [5]:
print(D2)

[[ 6  4  4  8]
 [11 11  4  1]
 [ 6  7 18  9]]


# Task 3-Find the minimum and maximum values in a NumPy array

In [6]:
#finding minimum value from the array 
D2.min()

1

In [7]:
# finding maximum value from the array 
D2.max()

18

# Task 4- Calculate the mean, median, and standard deviation of a given NumPy array.

In [8]:
# calculating the mean of array
R = np.mean(D2)
print(R)

7.416666666666667


In [9]:
# calculating the median of array
R2 = np.median(D2)
print(R2)

6.5


In [10]:
R3 = np.std(D2)
print(R3)

4.2906552206186666


# Task 5- Extract all the odd numbers from a given NumPy array.

In [11]:
pt= d1[d1 % 2 != 0]

In [12]:
print(pt)

[11 11  1  7  9]
