# Tasks for one hot and label encoder , apply the same task in different datasets from kaggle

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn import preprocessing

In [2]:
# Load the dataset
df = pd.read_csv('Iris.csv')

In [3]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
from sklearn import preprocessing

In [6]:
df['Species2']=lable_encoder.fit_transform(df['Species'])

In [7]:
df['SepalLengthCm'].unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [8]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [9]:
df['Species2'].unique()

array([0, 1, 2])

In [10]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  Species2  
0       Iris-setosa         0  
1       Iris-setosa         0  
2       Iris-setosa         0  
3       Iris-setosa         0  
4       Iris-setosa         0  
..              ...       ...  
145  Iris-virginica         2  
146  Iris-virginica         2  
147  Iris-virginica         2  
148  Iris-virginica         2  
149  Iris-virginica         2  

[150 rows x 7 columns]

In [11]:
df['SepalWidthCm'].unique()

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, 4. , 4.4, 3.8, 3.3,
       4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

# One-hot using get_dummies() in pandas

In [12]:
pd.get_dummies(df,columns=["Species"])

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species2  \
0      1            5.1           3.5            1.4           0.2         0   
1      2            4.9           3.0            1.4           0.2         0   
2      3            4.7           3.2            1.3           0.2         0   
3      4            4.6           3.1            1.5           0.2         0   
4      5            5.0           3.6            1.4           0.2         0   
..   ...            ...           ...            ...           ...       ...   
145  146            6.7           3.0            5.2           2.3         2   
146  147            6.3           2.5            5.0           1.9         2   
147  148            6.5           3.0            5.2           2.0         2   
148  149            6.2           3.4            5.4           2.3         2   
149  150            5.9           3.0            5.1           1.8         2   

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica  
0                      1                        0                       0  
1                      1                        0                       0  
2                      1                        0                       0  
3                      1                        0                       0  
4                      1                        0                       0  
..                   ...                      ...                     ...  
145                    0                        0                       1  
146                    0                        0                       1  
147                    0                        0                       1  
148                    0                        0                       1  
149                    0                        0                       1  

[150 rows x 9 columns]

In [13]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  Species2  
0       Iris-setosa         0  
1       Iris-setosa         0  
2       Iris-setosa         0  
3       Iris-setosa         0  
4       Iris-setosa         0  
..              ...       ...  
145  Iris-virginica         2  
146  Iris-virginica         2  
147  Iris-virginica         2  
148  Iris-virginica         2  
149  Iris-virginica         2  

[150 rows x 7 columns]

In [14]:
pd.get_dummies(df,columns=["SepalLengthCm"]).head(10)

Id  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  Species2  \
0   1           3.5            1.4           0.2  Iris-setosa         0   
1   2           3.0            1.4           0.2  Iris-setosa         0   
2   3           3.2            1.3           0.2  Iris-setosa         0   
3   4           3.1            1.5           0.2  Iris-setosa         0   
4   5           3.6            1.4           0.2  Iris-setosa         0   
5   6           3.9            1.7           0.4  Iris-setosa         0   
6   7           3.4            1.4           0.3  Iris-setosa         0   
7   8           3.4            1.5           0.2  Iris-setosa         0   
8   9           2.9            1.4           0.2  Iris-setosa         0   
9  10           3.1            1.5           0.1  Iris-setosa         0   

   SepalLengthCm_4.3  SepalLengthCm_4.4  SepalLengthCm_4.5  SepalLengthCm_4.6  \
0                  0                  0                  0                  0   
1                  0                  0                  0                  0   
2                  0                  0                  0                  0   
3                  0                  0                  0                  1   
4                  0                  0                  0                  0   
5                  0                  0                  0                  0   
6                  0                  0                  0                  1   
7                  0                  0                  0                  0   
8                  0                  1                  0                  0   
9                  0                  0                  0                  0   

   ...  SepalLengthCm_6.8  SepalLengthCm_6.9  SepalLengthCm_7.0  \
0  ...                  0                  0                  0   
1  ...                  0                  0                  0   
2  ...                  0                  0                  0   
3  ...                  0                  0                  0   
4  ...                  0                  0                  0   
5  ...                  0                  0                  0   
6  ...                  0                  0                  0   
7  ...                  0                  0                  0   
8  ...                  0                  0                  0   
9  ...                  0                  0                  0   

   SepalLengthCm_7.1  SepalLengthCm_7.2  SepalLengthCm_7.3  SepalLengthCm_7.4  \
0                  0                  0                  0                  0   
1                  0                  0                  0                  0   
2                  0                  0                  0                  0   
3                  0                  0                  0                  0   
4                  0                  0                  0                  0   
5                  0                  0                  0                  0   
6                  0                  0                  0                  0   
7                  0                  0                  0                  0   
8                  0                  0                  0                  0   
9                  0                  0                  0                  0   

   SepalLengthCm_7.6  SepalLengthCm_7.7  SepalLengthCm_7.9  
0                  0                  0                  0  
1                  0                  0                  0  
2                  0                  0                  0  
3                  0                  0                  0  
4                  0                  0                  0  
5                  0                  0                  0  
6                  0                  0                  0  
7                  0                  0                  0  
8                  0                  0                  0  
9                  0                  0      

# One-hot using ML

In [15]:
one_hot=OneHotEncoder()

In [16]:
x=one_hot.fit_transform(df[["PetalWidthCm"]]).toarray()

In [17]:
x.reshape(-1,1)

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [18]:
x.shape

(150, 22)

In [19]:
feature_name=one_hot.get_feature_names_out(["PetalWidthCm"])

In [20]:
feature_name

array(['PetalWidthCm_0.1', 'PetalWidthCm_0.2', 'PetalWidthCm_0.3',
       'PetalWidthCm_0.4', 'PetalWidthCm_0.5', 'PetalWidthCm_0.6',
       'PetalWidthCm_1.0', 'PetalWidthCm_1.1', 'PetalWidthCm_1.2',
       'PetalWidthCm_1.3', 'PetalWidthCm_1.4', 'PetalWidthCm_1.5',
       'PetalWidthCm_1.6', 'PetalWidthCm_1.7', 'PetalWidthCm_1.8',
       'PetalWidthCm_1.9', 'PetalWidthCm_2.0', 'PetalWidthCm_2.1',
       'PetalWidthCm_2.2', 'PetalWidthCm_2.3', 'PetalWidthCm_2.4',
       'PetalWidthCm_2.5'], dtype=object)

In [21]:
df3=pd.DataFrame(x,columns=feature_name)

In [22]:
df3

PetalWidthCm_0.1  PetalWidthCm_0.2  PetalWidthCm_0.3  PetalWidthCm_0.4  \
0                 0.0               1.0               0.0               0.0   
1                 0.0               1.0               0.0               0.0   
2                 0.0               1.0               0.0               0.0   
3                 0.0               1.0               0.0               0.0   
4                 0.0               1.0               0.0               0.0   
..                ...               ...               ...               ...   
145               0.0               0.0               0.0               0.0   
146               0.0               0.0               0.0               0.0   
147               0.0               0.0               0.0               0.0   
148               0.0               0.0               0.0               0.0   
149               0.0               0.0               0.0               0.0   

     PetalWidthCm_0.5  PetalWidthCm_0.6  PetalWidthCm_1.0  PetalWidthCm_1.1  \
0                 0.0               0.0               0.0               0.0   
1                 0.0               0.0               0.0               0.0   
2                 0.0               0.0               0.0               0.0   
3                 0.0               0.0               0.0               0.0   
4                 0.0               0.0               0.0               0.0   
..                ...               ...               ...               ...   
145               0.0               0.0               0.0               0.0   
146               0.0               0.0               0.0               0.0   
147               0.0               0.0               0.0               0.0   
148               0.0               0.0               0.0               0.0   
149               0.0               0.0               0.0               0.0   

     PetalWidthCm_1.2  PetalWidthCm_1.3  ...  PetalWidthCm_1.6  \
0                 0.0               0.0  ...               0.0   
1                 0.0               0.0  ...               0.0   
2                 0.0               0.0  ...               0.0   
3                 0.0               0.0  ...               0.0   
4                 0.0               0.0  ...               0.0   
..                ...               ...  ...               ...   
145               0.0               0.0  ...               0.0   
146               0.0               0.0  ...               0.0   
147               0.0               0.0  ...               0.0   
148               0.0               0.0  ...               0.0   
149               0.0               0.0  ...               0.0   

     PetalWidthCm_1.7  PetalWidthCm_1.8  PetalWidthCm_1.9  PetalWidthCm_2.0  \
0                 0.0               0.0               0.0               0.0   
1                 0.0               0.0               0.0               0.0   
2                 0.0               0.0               0.0               0.0   
3                 0.0               0.0               0.0               0.0   
4                 0.0               0.0               0.0               0.0   
..                ...               ...               ...               ...   
145               0.0               0.0               0.0               0.0   
146               0.0               0.0               1.0               0.0   
147               0.0               0.0               0.0               1.0   
148               0.0               0.0               0.0               0.0   
149               0.0               1.0               0.0               0.0   

     PetalWidthCm_2.1  PetalWidthCm_2.2  PetalWidthCm_2.3  PetalWidthCm_2.4  \
0                 0.0               0.0               0.0               0.0   
1                 0.0               0.0               0.0               0.0   
2                 0.0               0.0               0.0               0.0   
3                 0.0               0.0          

# Label encoder using ML

In [25]:
lable_encoder=preprocessing.LabelEncoder()

In [44]:
# Encode labels in column 'species'.
df['species2']= lable_encoder.fit_transform(df['Species'])

In [45]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [46]:
Z=df['Species']

In [47]:
print(Z)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object


In [48]:
df['species2'].unique()

array([0, 1, 2])

In [50]:
df['species2']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species2, Length: 150, dtype: int32

In [56]:
# Print the encoded labels
print("Encoded labels:", df['species2'])

Encoded labels: 0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species2, Length: 150, dtype: int32


In [57]:
# Decode the labels
decoded = lable_encoder.inverse_transform(df['species2'])

In [58]:
# Print the decoded labels
print("Decoded labels:", decoded)

Decoded labels: ['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 